[211116] 정하영
pangpang-study/algorithm-coding-test-study pull request #56
Opened 2021-11-30 08:13 UTC by hydenny

### 한 줄 소감
`한 줄 소감을 쓰시오`

## 1번 문제 풀이
### 문제 분석
이 문제는...

### 풀이 방법
1. 이 문제는...

### 포인트
이 문제의 포인트는...

## 2번 문제 풀이
### 문제 분석
이 문제는...

### 풀이 방법
1. 이 문제는...

### 포인트
이 문제의 포인트는...

## 3번 문제 풀이
### 문제 분석
이 문제는...

### 풀이 방법
1. 이 문제는...

### 포인트
이 문제의 포인트는...

2021-11-30 14:32 UTC, YuHyeonGeun-KOR submitted a review, later dismissed

2021-12-01 01:59 UTC, Akgop requested changes
가르침 못 푼거 풀고 다시 커밋 올려주세요

2021-12-01 01:59 UTC, Akgop commented on jhy/211116/Yonsei TOTO.py
> +import sys
개인적으로 import는 코드 맨 위에 있었으면 좋겠습니다.

2021-12-01 01:59 UTC, Akgop commented on jhy/211116/가르침.py
> +                count += 1
이 부분이 왜 따로 필요한지 모르겠습니다.

수도코드를 너무 경우의 수를 많이 나눠서 생각하신것 같습니다. 일관되게 짜면 오히려 더 쉽게 풀릴것 같습니다.
문제가 80%에서 틀렸습니다 라고 나온다면 이 부분때문이 아니라 아예 31~54 라인에서 그냥 아이디어가 틀려서 그럴 수도 있으니 싹 지우고 처음부터 다시 풀어보는걸 추천드립니다.

2021-12-01 13:02 UTC, hydenny commented on jhy/211116/Yonsei TOTO.py
> +import sys
@Akgop 넵 수정완료했습니다!

2021-12-01 13:03 UTC, hydenny commented on jhy/211116/가르침.py
> +                count += 1
@Akgop 넵 아예 처음부터 다시 풀어보도록 하겠습니다.

2021-12-03 14:42 UTC, YuHyeonGeun-KOR approved these changes

2021-12-07 02:31 UTC, Akgop approved these changes

2021-12-07 02:36 UTC, YuHyeonGeun-KOR approved these changes

2021-12-07 11:42 UTC, hanuk96 approved these changes

2021-12-07 11:42 UTC, merged