[211207] 유한욱
pangpang-study/algorithm-coding-test-study pull request #69
Opened 2021-12-15 05:02 UTC by hanuk96

### 한 줄 소감
`한 줄 소감을 쓰시오`

## 1번 문제 풀이
### 문제 분석
이 문제는...

### 풀이 방법
1. 이 문제는...

### 포인트
이 문제의 포인트는...

## 2번 문제 풀이
### 문제 분석
이 문제는...

### 풀이 방법
1. 이 문제는...

### 포인트
이 문제의 포인트는...

## 3번 문제 풀이
### 문제 분석
이 문제는...

### 풀이 방법
1. 이 문제는...

### 포인트
이 문제의 포인트는...

2021-12-17 17:48 UTC, Akgop approved these changes

2021-12-17 17:48 UTC, Akgop commented on yhw/211207/지뢰찾기.java
> +			}
char 형이라 -- 연산자 되는거 좀 좋네요

2021-12-18 14:59 UTC, hydenny commented
@hanuk96 지뢰찾기 3-1 풀이에 지뢰를 임의로 일단 존재한다고 전부 설정해놓고 지뢰가 있다고 가정한 좌표 기준 그 주변에 0이 있음을 확인해서 0이 있는 경우에 대한 지뢰를 제거해준다는게 맞나요?

2021-12-19 03:12 UTC, hanuk96 commented on yhw/211207/지뢰찾기.java
> +			}
그렇죠 ㅎㅎ

2021-12-19 03:13 UTC, hanuk96 commented
> @hanuk96 지뢰찾기 3-1 풀이에 지뢰를 임의로 일단 존재한다고 전부 설정해놓고 지뢰가 있다고 가정한 좌표 기준 그 주변에 0이 있음을 확인해서 0이 있는 경우에 대한 지뢰를 제거해준다는게 맞나요?
0이 있는거는 체크용
0이 없다는게 확인이 되면 지뢰가 무조건 있어야 판단(최대이므로) -> 8방향의 좌표들의 숫자값을 1 줄임

2021-12-19 05:05 UTC, Akgop requested changes

2021-12-19 05:05 UTC, Akgop commented on yhw/211207/미세먼지안녕.java
> +			}
35번째 라인에서 dust.add를 하는데 40번째 라인에서 dust.get을 해서 dust Arraylist가 초기화되지 않고 계속 쌓입니다.

그래서 22번째 라인 dust 초기화 하는 부분을 31번째라인 이후로 옮겨야 하면 해결될 것 같습니다.

2021-12-19 12:59 UTC, hydenny commented
> > @hanuk96 지뢰찾기 3-1 풀이에 지뢰를 임의로 일단 존재한다고 전부 설정해놓고 지뢰가 있다고 가정한 좌표 기준 그 주변에 0이 있음을 확인해서 0이 있는 경우에 대한 지뢰를 제거해준다는게 맞나요?
> > 0이 있는거는 체크용
> > 0이 없다는게 확인이 되면 지뢰가 무조건 있어야 판단(최대이므로) -> 8방향의 좌표들의 숫자값을 1 줄임

확인했습니다 감사합니다~

2021-12-19 12:59 UTC, hydenny approved these changes

2021-12-28 11:09 UTC, merged